### ISSUE TITLE
Create branch for UFS SRW App release 1.0

### ISSUE THREAD

**Issue by climbfuji** [noaa-psd/stochastic_physics#29]
We need to create branch `release/public-v2` for the upcoming SRW App v1.0 release. This branch should be at hash
```
commit a8e2cc1c84a1e6a7deb9eef152edec2992b1a859 (HEAD)
Merge: 9a791d4 a06fd42
Author: Phil Pegion <38869668+pjpegion@users.noreply.github.com>
Date:   Thu Aug 6 08:54:12 2020 -0600

    Merge pull request #27 from climbfuji/stochastic_physics_independent_of_fv3atm

    Make stochastic physics independent of fv3atm and its submodules
```
@pjpegion can you please do that?

**Comment by pjpegion** [comment]
Are you sure about calling it release/public-v2?  What happens when we release MRW app v2?  I would prefer calling it release/public-swr-v1 or something of the sort.

**Comment by climbfuji** [comment]
> Are you sure about calling it release/public-v2? What happens when we release MRW app v2? I would prefer calling it release/public-swr-v1 or something of the sort.

This was the agreement that everyone else used, see https://github.com/ufs-community/ufs-srweather-app/issues/19. A few repositories have slightly different names or numbers, depending on whether they also release with other models than the UFS models. MRW App v2 would be using release/public-vX whatever that X is going to be.

**Comment by climbfuji** [comment]
> > Are you sure about calling it release/public-v2? What happens when we release MRW app v2? I would prefer calling it release/public-swr-v1 or something of the sort.
> 
> This was the agreement that everyone else used, see [ufs-community/ufs-srweather-app#19](https://github.com/ufs-community/ufs-srweather-app/issues/19). A few repositories have slightly different names or numbers, depending on whether they also release with other models than the UFS models. MRW App v2 would be using release/public-vX whatever that X is going to be.

The reasoning is that ufs-weather-model is the same component and whenever it is released with a substantial change, it gets a new version number. Note that ufs-weather-model release/public-v2 goes together with SRW App release 1.0.

**Comment by pjpegion** [comment]
ok. I will do it, but I don't think we should be jumping whole numbers. perhaps v1.2 since the code for MRW and SRW is not that different for the model.

Branch is there.

**Comment by climbfuji** [comment]
Thanks, @pjpegion . Please note that the code changes may be minor for stochastic_physics, but they are major for other components of the ufs-weather-model.
