### ISSUE TITLE
Quad precision not supported on Apple Silicon Arm64 architecture?

### ISSUE THREAD

**Issue by climbfuji** [noaa-psd/stochastic_physics#52]
The following piece of code does not compile on Apple Arm64 (i.e. new Apple Silicon M1 chips):
```
https://github.com/noaa-psd/stochastic_physics/blob/ef248edea04da19ac5300075cc042e4efebebd8a/kinddef.F90#L19
```
It seems that, according to https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms, 16-bit reals are not supported. Instead of defining the quad precision type based on PGI or not, I would advocate for a CPP definition that can be enable/disabled by the build system / the user, like it is done for FMS (`-DENABLE_QUAD_PRECISION`).

**Comment by climbfuji** [comment]
Or, alternatively, like in the dycore `GFDL_atmos_cubed_sphere`:
```
-DNO_QUAD_PRECISION
```

**Comment by pjpegion** [comment]
I will have to test the impact of that simple change.  These values are quad precision for a reason, but it may only be needed for really high resolution grids.  If that is the case, we need to document the limitation of running on this architecture.

**Comment by pjpegion** [comment]
The iteration is getting stuck in an infinite loop

**Comment by climbfuji** [comment]
Hmm not sure what to do with this. How about PGI? The code already had the PGI exception in there.

**Comment by pjpegion** [comment]
I will look into the issue.

**Comment by pjpegion** [comment]
@DomHeinzeller It is working now.  I put NO_QUAD_PRECISION logic in spectral_transforms to increase the tolerance limit for the iteration.  I can issue the PR with the fix.
